#!/bin/bash

IN=$(xrandr | grep -E "\bconnected\b" | grep -ohP "LVDS-\d")
EXT=$(xrandr | grep -E "\bconnected\b" | grep -ohP "VGA-\d")

if [[ -n $EXT ]]; then
    xrandr --output $IN --off --output $EXT --primary --auto
else
    xrandr --output $EXT --off --output $IN --primary --auto
fi
